version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000 # expose ports - HOST:CONTAINER
    volumes:
      - './server:/usr/src/app'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000 # expose ports - HOST:CONTAINER
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    links:
      - server